
log = console.log
extractModuleInfo = (js)->
  _ = require 'lodash'
  parser = require("uglify-js").parser
  proc = require("uglify-js").uglify

  toCode = (astCode) ->
    code = proc.gen_code(astCode, { beautify: true })

  # helper, keeping main uglify's notation
  readAst=
    "call": (ast)->
      expr = ast[1]
      name = dot = ''
      dotExpr = expr
      while dotExpr[0] is 'dot' #extract dotted references (eg my.object.method)
        name = "#{dotExpr[2]}#{dot}#{name}"
        dotExpr = dotExpr[1]
        dot = '.'

      name = dotExpr[1] + dot + name

      return {
        callName:name
        expr:expr
        args:ast[2]
      }

  #  "function": (ast)->
  #    name:ast[0]
  #    args:ast[1]
  #    body:ast[2]
  #
  #
  #  "defun": (ast)->
  #    name:ast[0]
  #    args:ast[1]
  #    body:ast[2]

  m = {}
  stop = false
  stack = [];
  walkTree = (oa, ident)-> # ident is only used for debugging
    if not stop
      ident = if ident then ident + "    " else " "
      _.each oa, (val, key)->
        if _.isObject(val) or _.isArray(val)
          stack.push val
          walkTree(val, ident)
          stack.pop()
        else
          stacktop = stack[stack.length-1]
#          log '*************** \n'
#          log stacktop, '\n'
          if val is 'object' and stacktop[1][0][0] is 'module'
            moduleAst = stacktop[1][0][1]
            m = _.extend m, eval("(#{toCode(moduleAst)})")
          if val is 'call'
            call = readAst['call'](stacktop)
            if call.callName in ['define', 'require']
              # check for 'standard' AMD signature
              if call.args.length is 2 and call.args[0][0] is 'array' and call.args[1][0] is 'function'
                m.type = call.callName # 'define' or 'require'
                m.dependencies = eval toCode call.args[0] # array of deps ['dep1', 'dep2']
                m.parameters = call.args[1][2] # args of function - 2nd arg of define - (dep1, dep2)
                m.factoryBody = ''
                for bodyStatement in call.args[1][3] # all statements of function body
                  m.factoryBody += toCode(bodyStatement) + "\n"
                stop = true

  walkTree parser.parse(js) # recursive walker - stores in m

  return m

module.exports = extractModuleInfo

#log "\n## module info ##"
#log extractModuleInfo """
#// Generated by CoffeeScript 1.3.3
#({
#  module: {
#    rootExports: 'globalVar'
#  }
#});
#
#if (typeof define !== 'function') { var define = require('amdefine')(module) };
#
#define(['depdir2/depdir3/dep3'], function(dep3) {
#  console.log("\n dep2 starting....");
#  return function() {
#    return 'dep2: Hello world, ' + dep3();
#  };
#});
#"""
#log "################### \n"

